services:
  mongoDb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ali
      - MONGO_INITDB_ROOT_PASSWORD=ali
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=ali
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=ali
      - ME_CONFIG_MONGODB_URL=mongodb://ali:ali@mongo_db:27017
      - ME_CONFIG_BASICAUTH=false

volumes:
  mongo: {}
